/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditalRouteImport } from './routes/edital'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as FocoRouteImport } from './routes/foco'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as RedacaoRouteImport } from './routes/redacao'
import { Route as SimuladoRouteImport } from './routes/simulado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditalRoute = EditalRouteImport.update({
  id: '/edital',
  path: '/edital',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const FocoRoute = FocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoRoute = RedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoRoute = SimuladoRouteImport.update({
  id: '/simulado',
  path: '/simulado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/edital': typeof EditalRoute
  '/flashcards': typeof FlashcardsRoute
  '/foco': typeof FocoRoute
  '/onboarding': typeof OnboardingRoute
  '/questoes': typeof QuestoesRoute
  '/redacao': typeof RedacaoRoute
  '/simulado': typeof SimuladoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/edital': typeof EditalRoute
  '/flashcards': typeof FlashcardsRoute
  '/foco': typeof FocoRoute
  '/onboarding': typeof OnboardingRoute
  '/questoes': typeof QuestoesRoute
  '/redacao': typeof RedacaoRoute
  '/simulado': typeof SimuladoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/edital': typeof EditalRoute
  '/flashcards': typeof FlashcardsRoute
  '/foco': typeof FocoRoute
  '/onboarding': typeof OnboardingRoute
  '/questoes': typeof QuestoesRoute
  '/redacao': typeof RedacaoRoute
  '/simulado': typeof SimuladoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/edital'
    | '/flashcards'
    | '/foco'
    | '/onboarding'
    | '/questoes'
    | '/redacao'
    | '/simulado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/edital'
    | '/flashcards'
    | '/foco'
    | '/onboarding'
    | '/questoes'
    | '/redacao'
    | '/simulado'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/edital'
    | '/flashcards'
    | '/foco'
    | '/onboarding'
    | '/questoes'
    | '/redacao'
    | '/simulado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EditalRoute: typeof EditalRoute
  FlashcardsRoute: typeof FlashcardsRoute
  FocoRoute: typeof FocoRoute
  OnboardingRoute: typeof OnboardingRoute
  QuestoesRoute: typeof QuestoesRoute
  RedacaoRoute: typeof RedacaoRoute
  SimuladoRoute: typeof SimuladoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edital': {
      id: '/edital'
      path: '/edital'
      fullPath: '/edital'
      preLoaderRoute: typeof EditalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foco': {
      id: '/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof FocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao': {
      id: '/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof RedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado': {
      id: '/simulado'
      path: '/simulado'
      fullPath: '/simulado'
      preLoaderRoute: typeof SimuladoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EditalRoute: EditalRoute,
  FlashcardsRoute: FlashcardsRoute,
  FocoRoute: FocoRoute,
  OnboardingRoute: OnboardingRoute,
  QuestoesRoute: QuestoesRoute,
  RedacaoRoute: RedacaoRoute,
  SimuladoRoute: SimuladoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
